language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
scala:
  - 2.10.4
  - 2.11.0-RC3
jdk:
  - openjdk8
notifications:
  email:
    - jason.zaugg@typesafe.com

# TODO add publishLocal to the commands to exercise doc generation (currently borked)
